# Generated by Django 2.0.3 on 2018-04-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=None, max_length=299),
            preserve_default=False,
        ),
    ]
