# Generated by Django 2.0.3 on 2018-04-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20180421_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accepted_follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='to_accept_follow', to='profiles.Profile'),
        ),
    ]
