# Generated by Django 2.0.3 on 2018-04-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20180423_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='request_follows',
            field=models.ManyToManyField(blank=True, related_name='requested_follows', to='profiles.Profile'),
        ),
    ]
